### PR TITLE
Log plugin errors to the console

### PR DESCRIPTION
**Pull request by thelfensdrfer**
Without this added line, errors raised by the plugin were not displayed in the sublime console.

### CODE REVIEW

**Comment by kaste** [comment]
What's the intent here, really. To provide a description isn't too much. Why shouldn't we listen to STDERR

**Comment by thelfensdrfer** [comment]
Sorry about that, added an description.

**Comment by kaste** [comment]
Ah, and that works? If we don't claim STDERR Sublime wires it up for us. 

Most plugins actually capture the errors (hence this is the default) and then don't know ... log them LOL

**Comment by thelfensdrfer** [comment]
Yeah I don't know either. All I know is that this line fixed it for me ;)

**Comment by kaste** [comment]
Yeah, cool. I'll take it without the merge conflicts. 😛

**Pull request merged**
